engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/ClassAndModuleChildren:
        enabled: false
ratings:
   paths:
   - api/app/**
exclude_paths:
- api/test/**/*
- api/vendor/**/*