engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/ClassAndModuleChildren:
        enabled: false
  bundler-audit:
    enabled: true
ratings:
   paths:
   - app/**
exclude_paths:
- test/**/*
- vendor/**/*