engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/ClassAndModuleChildren:
        EnforcedStyle: compact
  bundler-audit:
    enabled: true
ratings:
   paths:
   - app/**
   - lib/**
   - "**.rb"
exclude_paths:
- test/**/*
- vendor/**/*