# Needed to keep data for api
data_api:
  image: debian:jessie
  volumes:
    - ./api:/api

# Needed to keep data for frontend
data_frontend:
  image: debian:jessie
  volumes:
    - ./frontend:/api/public

# DB container
postgres:
  image: postgres
  env_file: docker/dev/.env

# Giving time for the db to start
dbcreator:
  build: .
  dockerfile: ./docker/dev/api/Dockerfile
  command: bash /docker/dbcreator/create.sh
  links:
    - postgres

# Running migrations
migrator:
  build: .
  dockerfile: ./docker/dev/api/Dockerfile
  command: bash /docker/migrator/migrate.sh
  volumes_from:
    - data_api:rw
  links:
    - postgres
  env_file: docker/dev/.env

# All about the rails is here
api:
  build: .
  dockerfile: ./docker/dev/api/Dockerfile
  command: bundle exec rails s -p 80 -b '0.0.0.0'
#  command: bundle exec yard server -p 3000 -b '0.0.0.0'
  volumes_from:
    - data_api:rw
    - data_frontend:rw
  ports:
    - "80:80"
  links:
    - postgres
  env_file: docker/dev/.env

# Running api tests
tester:
  build: .
  dockerfile: ./docker/dev/api/Dockerfile
  command: bash /docker/tester/test.sh
  volumes_from:
    - data_api:rw
  links:
    - postgres
  env_file: docker/dev/.env

# All about the frontend is here
frontend:
  build: .
  dockerfile: ./docker/dev/frontend/Dockerfile
  volumes_from:
    - data_frontend:rw
