# Needed to keep data
data:
  image: debian:jessie
  volumes:
    - .:/api

# DB container
postgres:
  image: postgres
  env_file: .env

# Giving time for the db to start
dbcreator:
  build: .
  dockerfile: ./docker/api/Dockerfile
  command: bash docker/dbcreator/create.sh
  links:
    - postgres

# Running migrations
migrator:
  build: .
  dockerfile: ./docker/api/Dockerfile
  command: bash docker/migrator/migrate.sh
  volumes_from:
    - data:rw
  links:
    - postgres
  env_file: .env

# All about the rails is here
api:
  build: .
  dockerfile: ./docker/api/Dockerfile
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes_from:
    - data:rw
  ports:
    - "3000:3000"
  links:
    - postgres
  env_file: .env

# Running api tests
tester:
  build: .
  dockerfile: ./docker/api/Dockerfile
  command: bash docker/tester/test.sh
  volumes_from:
    - data:rw
  links:
    - postgres
  env_file: .env
