# Needed to keep code
code:
  image: debian:jessie
  volumes:
    - .:/home/app/webapp

# Needed to keep data
data:
  image: debian:jessie
  volumes:
    - ./public:/home/app/data

# DB container
postgres:
  image: postgres
  env_file: docker/prod/.env

# All about the rails is here
api:
  build: .
  dockerfile: ./docker/prod/api/Dockerfile
#  command: chown -R app /home/app/webapp & ls
  volumes_from:
    - code:rw
    - data:rw
  ports:
    - "80:80"
  links:
    - postgres
  env_file: docker/prod/.env

# Giving time for the db to start
dbcreator:
  build: .
  dockerfile: ./docker/prod/api/Dockerfile
  command: bash docker/prod/dbcreator/create.sh
  links:
    - postgres

# Running migrations
migrator:
  build: .
  dockerfile: ./docker/prod/api/Dockerfile
  command: bash docker/prod/migrator/migrate.sh
  volumes_from:
    - data:rw
  links:
    - postgres
  env_file: docker/prod/.env

