# Needed to keep code
code_api:
  image: debian:jessie
  volumes:
    - ./api:/home/app/webapp

# Needed to keep code for frontend
code_frontend:
  image: debian:jessie
  volumes:
    - ./frontend:/home/app/static

# Needed to keep data
data:
  image: debian:jessie
  volumes:
    - ./data:/home/app/data

# Needed to keep data for db
data_postgres:
  image: debian:jessie
  volumes:
    - ./pgdata:/var/lib/postgresql/data

# Needed to keep logs
logs:
  image: debian:jessie
  volumes:
    - ./logs:/home/app/logs

# DB container
postgres:
  image: postgres
  env_file: docker/prod/.env
  volumes_from:
      - data_postgres:rw

# All about the rails is here
api:
  build: .
  dockerfile: ./docker/prod/api/Dockerfile
  volumes_from:
    - code_api:rw
    - code_frontend:ro
    - data:rw
    - logs:rw
  ports:
    - "80:80"
  links:
    - postgres
  env_file: docker/prod/.env

# Running migrations
migrator:
  build: .
  dockerfile: ./docker/prod/migrator/Dockerfile
  command: bash /docker/migrator/migrate.sh
  volumes_from:
    - code_api:rw
  links:
    - postgres
  env_file: docker/prod/.env

# All about the frontend is here
frontend:
  build: .
  dockerfile: ./docker/prod/frontend/Dockerfile
  command: bash -c "npm install && bower install --allow-root && gulp build"
  volumes_from:
    - code_frontend:rw

