test:
  - action: User::Command::LogoutCommand
  - action: User::Command::ConfirmCommand
    token: :confirmation
  - action: User::Command::RecoveryCommand
    token: :recovery
  - action: User::Command::PinSetCommand
  - action: User::Command::PinCheckCommand
  - action: File::Command::PhotoCreateCommand
  - action: File::Command::PhotoIndexCommand
  - action: File::Command::PhotoDeleteCommand