test:
  # User
  - action: User::Command::LogoutCommand
  - action: User::Command::ConfirmCommand
    token: :confirmation
  - action: User::Command::RecoveryCommand
    token: :recovery
  - action: User::Command::PinSetCommand
  - action: User::Command::PinCheckCommand
  - action: User::Command::ViewCommand
  # File
  - action: File::Command::PhotoCreateCommand
  - action: File::Command::PhotoIndexCommand
  - action: File::Command::PhotoDeleteCommand
    owner: true
  # Family
  - action: Family::Command::FamilyUpdateCommand
  - action: Family::Command::FamilyViewCommand
  - action: Family::Command::PersonCreateCommand
  - action: Family::Command::PersonUpdateCommand
    owner: true
  - action: Family::Command::PersonDeleteCommand
    owner: true
  # Goal
  - action: Goal::Command::GoalCreateCommand
    owner: true
  - action: Goal::Command::GoalIndexCommand
    owner: true
  - action: Goal::Command::GoalUpdateCommand
    owner: true
  - action: Goal::Command::GoalDeleteCommand
    owner: true
  - action: Goal::Command::GoalViewCommand
    owner: true
  - action: Goal::Command::GoalPointsUpdateCommand
    owner: true