test:
  # User
  - action: User::Command::LogoutCommand
  - action: User::Command::ConfirmCommand
    token: :confirmation
  - action: User::Command::RecoveryCommand
    token: :recovery
  - action: User::Command::PinSetCommand
  - action: User::Command::PinCheckCommand
  - action: User::Command::ViewCommand
  # File
  - action: Uploaded::Command::PhotoCreateCommand
  - action: Uploaded::Command::PhotoIndexCommand
  - action: Uploaded::Command::PhotoDeleteCommand
  # Family
  - action: Family::Command::FamilyUpdateCommand
  - action: Family::Command::FamilyViewCommand
  - action: Family::Command::PersonCreateCommand
  - action: Family::Command::PersonUpdateCommand
  - action: Family::Command::PersonDeleteCommand
  # Goal
  - action: Goal::Command::GoalCreateCommand
  - action: Goal::Command::GoalIndexCommand
  - action: Goal::Command::GoalUpdateCommand
  - action: Goal::Command::GoalDeleteCommand
  - action: Goal::Command::GoalViewCommand
  - action: Goal::Command::GoalPointsUpdateCommand